<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="D-SHC-00436690" name="JUNIT SUTIE" tests="2" failures="1" timestamp="15 Nov 2012 07:39:33 GMT" time="492.726" errors="0">
  <testcase name="invoiceDataAccessTest" time="80.144" classname="com.paypal.test.riskmint.pph.service.InvoiceDataAccessingTest"/>
  <testcase name="invoiceDataAccessTest" time="412.535" classname="com.paypal.test.riskmint.pph.service.ProductFlagDataAccessingTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.paypal.test.riskmint.pph.service.ProductFlagDataAccessingTest.invoiceDataAccessTest(ProductFlagDataAccessingTest.java:41)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- invoiceDataAccessTest -->
</testsuite> <!-- JUNIT SUTIE -->
